### ISSUE TITLE
Feature: FSCTL_SET_ZERO_DATA 

### ISSUE THREAD

**Issue by xori** [mafintosh/fsctl#1]
In the future when hypercore starts needing to do garbage collection I've implemented the windows control codes for hole punching a sparse file with the [`FSCTL_SET_ZERO_DATA`](https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ni-winioctl-fsctl_set_zero_data) IoControl code. 

You can see the implementation here, feel free to use it or ping me to whip up a PR.
https://github.com/xori/set-sparse/blob/a6244dec1f67af92b0d9b627f47ad480f152cab8/src/sparse.cpp#L24-L42

This deallocates the file space on the hard drive between two points if it's large enough.

**Comment by mafintosh** [comment]
Oh that’s amazing! Was looking for that yesterday

**Comment by xori** [comment]
Ha, good timing. Yeah Windows C development sucks in my opinion, much more complicated than
```c
fallocate(fd, FALLOC_FL_PUNCH_HOLE, start, end)
```

**Comment by kasperisager** [comment]
There's an implementation of this in #3:

https://github.com/mafintosh/fsctl/blob/38710f79b5741f42160aa2eb24142f206c42b3bb/src/win.c#L81-L106
